### ISSUE TITLE
自定义sql不迁移索引到mysql

### ISSUE THREAD

**Issue by urbancabin** [iverycd/OracleSync2MySQL#11]
oracle有索引：
![image](https://github.com/iverycd/OracleSync2MySQL/assets/20166193/fa48cecc-9518-420b-b47e-7cbd2f8e874a)

执行迁移：
![image](https://github.com/iverycd/OracleSync2MySQL/assets/20166193/dc442a99-2c5b-4dab-adb4-ac4dbb7a4c60)
./OracleSync2MySQL --config example.yml -s 
![image](https://github.com/iverycd/OracleSync2MySQL/assets/20166193/d04705a7-2dbe-4784-a247-315c6f0e20a6)

mysql查看：
![image](https://github.com/iverycd/OracleSync2MySQL/assets/20166193/5508aa14-e5be-4cd6-90fb-fb50bd5b1a4c)

**Comment by urbancabin** [comment]
> 你好，目前自定义迁移只迁移表结构，是不会创建表结构之外的对象(索引、主键等)

请问下，那全库迁移的时候是支持索引、视图、主键吗？
![image](https://github.com/iverycd/OracleSync2MySQL/assets/20166193/b47c16e3-ebff-4f1a-acde-e2181c4f783c)

**Comment by iverycd** [comment]
> > 你好，目前自定义迁移只迁移表结构，是不会创建表结构之外的对象(索引、主键等)
> 
> 请问下，那全库迁移的时候是支持索引、视图、主键吗？ ![image](https://private-user-images.githubusercontent.com/20166193/312292373-b47c16e3-ebff-4f1a-acde-e2181c4f783c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTgxMzksIm5iZiI6MTcxMDI5NzgzOSwicGF0aCI6Ii8yMDE2NjE5My8zMTIyOTIzNzMtYjQ3YzE2ZTMtZWJmZi00ZjFhLWFjZGUtZTIxODFjNGY3ODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDBmMmNiNDFlZDdiMGNjYzNmZmVmZTFhMzIxZmViZDM5OWNkY2ZlMjRhNTNjMzk4MTk5OWRiNGYwYzY4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeRUs03SD_0mEaKY4PBNaMkL2pWsDTgRTW5fVGL4XNU)

全库迁移会迁移所有对象的

**Comment by urbancabin** [comment]
> > > 你好，目前自定义迁移只迁移表结构，是不会创建表结构之外的对象(索引、主键等)
> > 
> > 
> > 请问下，那全库迁移的时候是支持索引、视图、主键吗？ ![image](https://private-user-images.githubusercontent.com/20166193/312292373-b47c16e3-ebff-4f1a-acde-e2181c4f783c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTgxMzksIm5iZiI6MTcxMDI5NzgzOSwicGF0aCI6Ii8yMDE2NjE5My8zMTIyOTIzNzMtYjQ3YzE2ZTMtZWJmZi00ZjFhLWFjZGUtZTIxODFjNGY3ODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDBmMmNiNDFlZDdiMGNjYzNmZmVmZTFhMzIxZmViZDM5OWNkY2ZlMjRhNTNjMzk4MTk5OWRiNGYwYzY4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeRUs03SD_0mEaKY4PBNaMkL2pWsDTgRTW5fVGL4XNU)
> 
> 全库迁移会迁移所有对象的

好的 谢谢。   单表的后续会支持不~

**Comment by iverycd** [comment]
> > > > 你好，目前自定义迁移只迁移表结构，是不会创建表结构之外的对象(索引、主键等)
> > > 
> > > 
> > > 请问下，那全库迁移的时候是支持索引、视图、主键吗？ ![image](https://private-user-images.githubusercontent.com/20166193/312292373-b47c16e3-ebff-4f1a-acde-e2181c4f783c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTgxMzksIm5iZiI6MTcxMDI5NzgzOSwicGF0aCI6Ii8yMDE2NjE5My8zMTIyOTIzNzMtYjQ3YzE2ZTMtZWJmZi00ZjFhLWFjZGUtZTIxODFjNGY3ODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDBmMmNiNDFlZDdiMGNjYzNmZmVmZTFhMzIxZmViZDM5OWNkY2ZlMjRhNTNjMzk4MTk5OWRiNGYwYzY4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeRUs03SD_0mEaKY4PBNaMkL2pWsDTgRTW5fVGL4XNU)
> > 
> > 
> > 全库迁移会迁移所有对象的
> 
> 好的 谢谢。 单表的后续会支持不~

之前用Python写的项目是支持的，如果经常使用自定义迁移，需要迁移单表以及索引，我可以单独发给你之前写的老工具

**Comment by urbancabin** [comment]
> > > > > 你好，目前自定义迁移只迁移表结构，是不会创建表结构之外的对象(索引、主键等)
> > > > 
> > > > 
> > > > 请问下，那全库迁移的时候是支持索引、视图、主键吗？ ![image](https://private-user-images.githubusercontent.com/20166193/312292373-b47c16e3-ebff-4f1a-acde-e2181c4f783c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTgxMzksIm5iZiI6MTcxMDI5NzgzOSwicGF0aCI6Ii8yMDE2NjE5My8zMTIyOTIzNzMtYjQ3YzE2ZTMtZWJmZi00ZjFhLWFjZGUtZTIxODFjNGY3ODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyNDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDBmMmNiNDFlZDdiMGNjYzNmZmVmZTFhMzIxZmViZDM5OWNkY2ZlMjRhNTNjMzk4MTk5OWRiNGYwYzY4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeRUs03SD_0mEaKY4PBNaMkL2pWsDTgRTW5fVGL4XNU)
> > > 
> > > 
> > > 全库迁移会迁移所有对象的
> > 
> > 
> > 好的 谢谢。 单表的后续会支持不~
> 
> 之前用Python写的项目是支持的，如果经常使用自定义迁移，需要迁移单表以及索引，我可以单独发给你之前写的老工具

好的   那麻烦发下吧。 现在是全库执行后有部分出错，需要单独处理下~

**Comment by iverycd** [comment]
麻烦提供一个邮箱，老工具用Python写的，体积比较大

**Comment by urbancabin** [comment]
> 麻烦提供一个邮箱，老工具用Python写的，体积比较大

1182752696@qq.com  太感谢了~

**Comment by iverycd** [comment]
> > 麻烦提供一个邮箱，老工具用Python写的，体积比较大
> 
> [1182752696@qq.com](mailto:1182752696@qq.com) 太感谢了~

请查收，请查看文档末尾部分有迁移部分表介绍

**Comment by urbancabin** [comment]
> > > 麻烦提供一个邮箱，老工具用Python写的，体积比较大
> > 
> > 
> > [1182752696@qq.com](mailto:1182752696@qq.com) 太感谢了~
> 
> 请查收，请查看文档末尾部分有迁移部分表介绍

收到，太感谢了大佬  帮解决了这个棘手问题
