### ISSUE TITLE
源表中的conments字段注释 貌似不能同步到目标表中

### ISSUE THREAD

**Issue by devOfWei** [iverycd/OracleSync2MySQL#12]
源表中的conments字段注释 貌似不能同步到目标表中，请问是有开关还是？

**Comment by iverycd** [comment]
无单独开关，默认是全部迁移过去的，麻烦发下表结构中带有注释的示例

**Comment by devOfWei** [comment]
需要我怎么提供给你呢？

**Comment by devOfWei** [comment]
CREATE TABLE "C_BS"."T_MEMBER_ORG"
(    "MEMBERNO" NUMBER,
"ORGID" NUMBER,
"INTEGRAL" VARCHAR2(100),
"MEMBERVIPCARDNO" VARCHAR2(100),
"ISVIP" NUMBER NOT NULL ENABLE,
"TYPEMARK" VARCHAR2(1),
"AGENTID" NUMBER,
"SOURCE" NUMBER,
"CREATETIME" VARCHAR2(50),
"FLAG" VARCHAR2(1),
"UPDATEDATE" DATE,
"TRANSFORMDATE" DATE,
"ISHIDDEN" VARCHAR2(1),
"SIGN" VARCHAR2(1) DEFAULT 0,
"CLOUD_FLAG" VARCHAR2(1),
"TAOBAO_NICK_NAME" NVARCHAR2(32),
"BALANCE" NUMBER DEFAULT 0,
"FROZEN_BALANCE" NUMBER DEFAULT 0,
"VERSION" NUMBER DEFAULT 0,
"INTEGRAL_AMOUNT" VARCHAR2(64) DEFAULT 0,
"ISSTARSTORE" NUMBER(1,0) DEFAULT 1
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TBS_C_BS" ;
CREATE UNIQUE INDEX "C_BS"."IDX_UNQ_T_MEMBER_ORG" ON "C_BS"."T_MEMBER_ORG" ("MEMBERNO", "ORGID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TBS_C_BS" ;
CREATE INDEX "C_BS"."IDX_T_MEMBER_ORG_ORGID" ON "C_BS"."T_MEMBER_ORG" ("ORGID")
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TBS_C_BS" ;
GRANT UPDATE ON "C_BS"."T_MEMBER_ORG" TO "HTD_HL";
GRANT INSERT ON "C_BS"."T_MEMBER_ORG" TO "HTD_HL";
COMMENT ON TABLE C_BS.T_MEMBER_ORG IS '新代理人关系表';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.MEMBERNO IS '粉丝编号';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.ORGID IS '所属会员店';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.INTEGRAL IS '会员积分';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.MEMBERVIPCARDNO IS 'vip卡号';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.ISVIP IS '是否是vip';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.TYPEMARK IS '会员/代理人标记';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.AGENTID IS '所属代理人ID';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG."SOURCE" IS '111:app自主注册,121:微商城自主注册,112:app推荐注册,
122:微商城推荐注册,123:大屏注册,
211:商品开单,212:保险开单,213:充值开单,
311:基本信息录入,312:保险信息录入,313:劳务信息录入,314:历史订单录入,
411:专属网店变更,141:法人系统注册,
511:天猫云店入会 412:百度小程序授权登录';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.CREATETIME IS '创建时间';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.UPDATEDATE IS '更新时间';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.TRANSFORMDATE IS '粉丝转化时间';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.ISHIDDEN IS '是否隐藏（1：隐藏， 空不隐藏）';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.SIGN IS '1 星标 0和空非星标';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.CLOUD_FLAG IS '是否是云店会员 1：是 空：否';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.TAOBAO_NICK_NAME IS '淘宝昵称';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.BALANCE IS '会员余额';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.FROZEN_BALANCE IS '会员消费冻结余额';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.VERSION IS '版本号，用于锁定';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.INTEGRAL_AMOUNT IS '新会员积分';
COMMENT ON COLUMN C_BS.T_MEMBER_ORG.ISSTARSTORE IS '是否关注店铺 1 已关注(默认) 0 未关注';

**Comment by iverycd** [comment]
> 源表中的conments字段注释 貌似不能同步到目标表中，请问是有开关还是？

@devOfWei 已发布最新release，请试下
https://github.com/iverycd/OracleSync2MySQL/releases/tag/v0.1.1

**Comment by devOfWei** [comment]
已有，感谢
