### ISSUE TITLE
从Oracle迁移过来的表结构默认值丢失了

### ISSUE THREAD

**Issue by seta2012** [iverycd/OracleSync2MySQL#13]
大佬，你好，我从Oracle迁移到Mysql后出现表结构的默认值丢失的情况，以下是详细信息：
Oracle的版本是：
![image](https://github.com/iverycd/OracleSync2MySQL/assets/26806068/8770f069-6977-438b-9cff-85bc345175f4)
Mysql的版本是：8.0.25-230100

Oracle的简化ddl

CREATE TABLE "TB_DOCUMENT" 
   (	"DOCUMENT_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"IS_ENCRYPT" NUMBER(1,0) DEFAULT 0, 
	"IS_PRINT" NUMBER(1,0) DEFAULT 0, 
	 PRIMARY KEY ("DOCUMENT_ID")
   );

使用dbeaver查看的Oracle的表结构
![image](https://github.com/iverycd/OracleSync2MySQL/assets/26806068/6902dc33-0af9-4947-8945-dfd6495cdf34)

使用dbeaver查看的迁移后的MySQL的表结构
![image](https://github.com/iverycd/OracleSync2MySQL/assets/26806068/402c7b63-35e7-4317-9715-b5fa9fd8766f)

**Comment by iverycd** [comment]
@seta2012 你好，我发布了最新的release `v0.1.2`，麻烦再试下，如有使用问题，欢迎提新issue，非常感谢😊

**Comment by seta2012** [comment]
> @seta2012 你好，我发布了最新的release `v0.1.2`，麻烦再试下，如有使用问题，欢迎提新issue，非常感谢😊
感谢大佬，经过测试默认值已经加上了
