### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by aidenjac** [iverycd/OracleSync2MySQL#19]
我在电脑上已经配置好环境了，但是在运行的时候直接报错
![微信图片_20240606145558](https://github.com/iverycd/OracleSync2MySQL/assets/167184412/7ce1d0e7-233d-4a12-89af-5b4c637dc2aa)

**Comment by iverycd** [comment]
看下go环境依赖的库有没有安装或者配置
可使用go mod tidy完成库依赖安装

**Comment by aidenjac** [comment]
> 看看go环境依赖的库有没有安装或者配置 可使用go mod tidy完成库依赖安装

![1717657485816](https://github.com/iverycd/OracleSync2MySQL/assets/167184412/de7ae98e-955f-40d4-9553-255b0acb8516)
是因为我的目录里有中文吗，有影响吗，我没做过go的开发，对这个有点迷茫

**Comment by iverycd** [comment]
建议用下IDE打开项目，Goland打开项目后会自动检测环境和依赖问题

**Comment by aidenjac** [comment]
![微信图片_20240606190340](https://github.com/iverycd/OracleSync2MySQL/assets/167184412/524cd606-dba6-4b22-b20c-4f971b3d79cf)
我已经下载了，但是里面都是报错，没导入依赖吗

**Comment by aidenjac** [comment]
您好作者，我现在用您这个软件遇到了两个问题，我自己修改了一下代码，我发现我不能打成.exe的文件，这个后续更新的时候能顺便带一下判断吗，或者我自己该如何打包一下，期待您的回复，新手小白在线求教
1.字段转换的时候VARCHAR2(4000)长度的转换成TEXT
2.CLOB类型Oracle19c能设置默认值，但是mysql不支持转换的时候带了默认值，去掉默认值
![微信图片_20241018185012](https://github.com/user-attachments/assets/cd1dcfcc-c0ec-4636-ba95-313621f6dcda)

**Comment by aidenjac** [comment]
这是我打包的时候的操作，以及拉取依赖的操作
![Uploading 微信图片_20241018185308.png…]()

**Comment by aidenjac** [comment]
这是我打包的时候的操作，以及拉取依赖的操作
![微信图片_20241018185308](https://github.com/user-attachments/assets/1ee7dc8d-bcfd-498c-b794-bc2e16562dc5)

**Comment by iverycd** [comment]
> 您好作者，我现在用您这个软件遇到了两个问题，我自己修改了一下代码，我发现我不能打成.exe的文件，这个后续更新的时候能顺便带一下判断吗，或者我自己该如何打包一下，期待您的回复，新手小白在线求教 1.字段转换的时候VARCHAR2(4000)长度的转换成TEXT 2.CLOB类型Oracle19c能设置默认值，但是mysql不支持转换的时候带了默认值，去掉默认值 ![微信图片_20241018185012](https://private-user-images.githubusercontent.com/167184412/377838452-cd1dcfcc-c0ec-4636-ba95-313621f6dcda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNTk3MzgsIm5iZiI6MTcyOTI1OTQzOCwicGF0aCI6Ii8xNjcxODQ0MTIvMzc3ODM4NDUyLWNkMWRjZmNjLWMwZWMtNDYzNi1iYTk1LTMxMzYyMWY2ZGNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxMzUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWZhZTIxNzA3MWYzNzE1ZWQ4YThhOTc3MDFmNzE1YjJkMjdjN2FiOWVhNDQ2MGYyYzRjNTc0YjNkMzg0NTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8z7ridFm68laxzJQJ8Fd0QGktumLn23HNrT5wXkC5DY)





看下有没有用go module

![QQ_1729260294353](https://github.com/user-attachments/assets/444f5342-dcef-4c31-8802-a83c82aeba30)


看报错是godror库导入有问题，可能是没安装依赖，手动安装试下go get github.com/godror/godror@latest，最后在goland把环境能run之后再编译，

**Comment by aidenjac** [comment]
已经跑起来了，非常感谢开源的这个代码，我也做了一些修改
后续会考虑更新单独创建索引，视图这些选项吗，有可能几张表有问题，视图就创建不成功了，想重新把索引那些或者视图全量跑

**Comment by aidenjac** [comment]
我改动的地方索引还没测试，我想问作者你有需求去单独跑索引视图的吗，我这个菜狗估计弄不出这种
OracleSync2MySQL.exe  --config 配置文件 -m
比如说视图就
OracleSync2MySQL.exe  --config 配置文件 -v这种操作麻烦吗

**Comment by iverycd** [comment]
> 我改动的地方索引还没测试，我想问作者你有需求去单独跑索引视图的吗，我这个菜狗估计弄不出这种 OracleSync2MySQL.exe --config 配置文件 -m 比如说视图就 OracleSync2MySQL.exe --config 配置文件 -v这种操作麻烦吗

最近在写其他项目，后续可能会考虑增加其他属性单独迁移功能
